apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: docker.io/gynam/myapp:latest # 젠킨스가 빌드한 이미지 경로
        ports:
        - containerPort: 8080
